# path: /opt/prometheus/prometheus.yml
global:
  scrape_interval: 1s
  evaluation_interval: 15s
  query_log_file: /opt/prometheus/logs/prometheus.log

alerting:
  alertmanagers:
    - static_configs:
        - targets:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]
